name:                geoquest-validator
version:             0.1.0.0
github:              "githubuser/geoquest-validator"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/geoquest-validator#readme>

dependencies:
- base >= 4.7 && < 5
- Spock >= 0.14
- text
- aeson
- mtl
- http-types
- cryptonite
- bytestring
- utf8-string
- persistent
- persistent-template
- persistent-sqlite  # May not be needed in production
- monad-logger
- time
- esqueleto
- extra
- memory

default-extensions:
- OverloadedStrings
- RecordWildCards
- DeriveGeneric
- DeriveAnyClass
- DeriveFunctor

library:
  source-dirs: src

executables:
  geoquest-validator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geoquest-validator

tests:
  geoquest-validator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geoquest-validator
